<?php

namespace Database\Seeders;

use App\Models\Desa;
use App\Models\Kecamatan;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class KecamatanDesaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'Indralaya' => [
                'Desa Lubuk Sakti',
                'Desa Tanjung Gelam',
                'Desa Tanjung Agung',
                'Desa Tanjung Sejaro',
                'Desa Sakatiga Seberang',
                'Desa Muara Penimbung Ulu',
                'Desa Tanjung Seteko',
                'Desa Saka Tiga',
                'Desa Ulak Banding',
                'Desa Muara Penimbung Ilir',
                'Desa Talang Aur',
                'Desa Ulak Bedil',
                'Desa Penyandingan',
                'Desa Sudimampir',
                'Desa Ulak Segelung',
                'Desa Sejaro Sakti',
                'Desa Tunas Aur',
                'Kelurahan Indralaya Indah',
                'Kelurahan Indralaya Mulya',
                'Kelurahan Indralaya Raya',
            ],
            'Tanjung Batu' => [
                'Desa Seri Bandung',
                'Desa Seri Tanjung',
                'Desa Tanjung Tambak',
                'Desa Senuro Timur',
                'Desa Tanjung Baru Petai',
                'Desa Tanjung Batu Seberang',
                'Desa Pajar Bulan',
                'Desa Tanjung Atap',
                'Desa Tanjung Pinang I',
                'Desa Limbang Jaya I',
                'Desa Tanjung Laut',
                'Desa Burai',
                'Desa Sentul',
                'Desa Bangun Jaya',
                'Desa Tanjung Tambak Baru',
                'Desa Limbang Jaya II',
                'Desa Senuro Barat',
                'Desa Tanjung Pinang II',
                'Desa Tanjung Atap Barat',
                'Kelurahan Tanjung Batu',
                'Kelurahan Tanjung Batu Timur',
            ],
            'Muara Kuang' => [
                'Desa Munggu',
                'Desa Seri Menanti',
                'Desa Rantau Sialang',
                'Desa Kuang Anyar',
                'Desa Kasah',
                'Desa Tanabang Ulu',
                'Desa Seri Kembang',
                'Desa Nagasari',
                'Desa Suka Cinta',
                'Desa Kelampadu',
                'Desa Tanabang Ilir',
                'Desa Ramah Kasih',
                'Desa Sukajadi',
                'Kelurahan Muara Kuang',
            ],
            'Tanjung Raja' => [
                'Desa Suka Pindah',
                'Desa Tanjung Temiang',
                'Desa Seri Dalam',
                'Desa Kerinjing',
                'Desa Ulak Kerbau Baru',
                'Desa Ulak Kerbau Lama',
                'Desa Tanjung Agas',
                'Desa Siring Alam',
                'Desa Talang Balai Baru I',
                'Desa Talang Balai Lama',
                'Desa Skonjing',
                'Desa Tanjung Raja Selatan',
                'Desa Belanti',
                'Desa Tanjung Harapan',
                'Desa Talang Balai Baru II',
                'Kelurahan Tanjung Raja',
                'Kelurahan Tanjung Raja Barat',
                'Kelurahan Tanjung Raja Timur',
                'Kelurahan Tanjung Raja Utara',
            ],
            'Indralaya Selatan' => [
                'Desa Mandi Angin',
                'Desa Tanjung Lubuk',
                'Desa Tebing Gerinting Selatan',
                'Desa Arisan Gading',
                'Desa Tanjung Dayang Selatan',
                'Desa Beti',
                'Desa Meranjat I',
                'Desa Meranjat Ilir',
                'Desa Meranjat II',
                'Desa Sukaraja Lama',
                'Desa Sukaraja Baru',
                'Desa Tebing Gerinting Utara',
                'Desa Tanjung Dayang Utara',
                'Desa Meranjat III',
            ],
            'Pemulutan' => [
                'Desa Aurstanding',
                'Desa Sukarami',
                'Desa Muara Dua',
                'Desa Palu',
                'Desa Teluk Kecapi',
                'Desa Pelabuhan Dalam',
                'Desa Pemulutan Ulu',
                'Desa Pemulutan Ilir',
                'Desa Sungai Rasau',
                'Desa Ibul Besar I',
                'Desa Pegayut',
                'Desa Simpang Pelabuhan Dalam',
                'Desa Ibul Besar II',
                'Desa Ibul Besar III',
                'Desa Mekar Jaya',
                'Desa Kedukan Bujang',
                'Desa Rawa Jaya',
                'Desa Babatan Saudagar',
                'Desa Tanjung Pasir',
                'Desa Harapan',
                'Desa Pipa Putih',
                'Desa Sungai Buaya',
                'Desa Muara Baru',
                'Desa Sembadak',
                'Desa Lebung Jangkar',
            ],
            'Pemulutan Barat' => [
                'Desa Suka Merindu',
                'Desa Sarang Lang',
                'Desa Kamal',
                'Desa Pulau Negara',
                'Desa Talang Pangeran Ulu',
                'Desa Ulak Kembahang I',
                'Desa Ulak Petangisan',
                'Desa Seri Banding',
                'Desa Ulak Kembahang II',
                'Desa Talang Pangeran Ilir',
                'Desa Arisan Jaya',
            ],
            'Rantau Alai' => [
                'Desa Sirah Pulau Kilip',
                'Desa Kelampaian',
                'Desa Sukananti',
                'Desa Sukamarga',
                'Desa Rantau Alai',
                'Desa Kerta Bayang',
                'Desa Tanjung Mas',
                'Desa Talang Sari',
                'Desa Lebung Bandung',
                'Desa Sanding Marga',
                'Desa Sukamaju',
                'Desa Mekar Sari',
                'Desa Sukananti Baru',
            ],
            'Indralaya Utara' => [
                'Desa Tanjung Pering',
                'Desa Bakung',
                'Desa Lorok',
                'Desa Parit',
                'Desa Payakabung',
                'Desa Sungai Rambutan',
                'Desa Purna Jaya',
                'Desa Soak Batok',
                'Desa Tanjung Baru',
                'Desa Tanjung Pule',
                'Desa Permata Baru',
                'Desa Suka Mulia',
                'Desa Pulau Kabal',
                'Desa Pulau Semambu',
                'Desa Palem Raya',
                'Kelurahan Timbangan',
            ],
            'Pemulutan Selatan' => [
                'Desa Pematang Bangsal',
                'Desa Maya Pati',
                'Desa Sungai Lebung',
                'Desa Kapuk',
                'Desa Ulak Aurstanding',
                'Desa Maju Jaya',
                'Desa Naikan Tembakang',
                'Desa Segayam',
                'Desa Cahaya Marga',
                'Desa Sungai Lebung Ulu',
                'Desa Sungai Keli',
                'Desa Lebak Pering',
                'Desa Sungai Ondok',
                'Desa Harimau Tandang',
                'Desa Pematang Bungur',
            ],
            'Rantau Panjang' => [
                'Desa Kotadaro I',
                'Desa Ketapang I',
                'Desa Rantau Panjang Ilir',
                'Desa Jagaraja',
                'Desa Jagalano',
                'Desa Sejangko I',
                'Desa Kota Daro II',
                'Desa Sungai Rotan',
                'Desa Rantau Panjang Ulu',
                'Desa Ketapang II',
                'Desa Sejangko II',
                'Desa Arisan Deras',
            ],
            'Sungai Pinang' => [
                'Desa Serijabo',
                'Desa Sungai Pinang II',
                'Desa Talang Dukun',
                'Desa Tanjung Serian',
                'Desa Penyandingan',
                'Desa Sungai Pinang III',
                'Desa Pinang Jaya',
                'Desa Sungai Pinang I',
                'Desa Pinang Mas',
                'Desa Sungai Pinang Lagati',
                'Desa Sungai Pinang Nibung',
                'Desa Serijabo Baru',
                'Kelurahan Sungai Pinang',
            ],
            'Kandis' => [
                'Desa Lubuk Rukam',
                'Desa Tanjung Alai',
                'Desa Kandis I',
                'Desa Kumbang Ulu',
                'Desa Kumbang Ilir',
                'Desa Miji',
                'Desa Santapan Barat',
                'Desa Pandan Arang',
                'Desa Muara Kumbang',
                'Desa Kandis II',
                'Desa Santapan Timur',
                'Desa Lubuk Segonang',
            ],
            'Rambang Kuang' => [
                'Desa Ibul Dalam',
                'Desa Beringin Dalam',
                'Desa Kuang Dalam Barat',
                'Desa Lubuk Tunggal',
                'Desa Ulak Segara',
                'Desa Tanjung Bulan',
                'Desa Tambang Rambang',
                'Desa Tangai',
                'Desa Kayu Ara',
                'Desa Tanjung Miring',
                'Desa Sunur',
                'Desa Kuang Dalam Timur',
                'Desa Sukananti',
            ],
            'Payaraman' => [
                'Desa Tebedak I',
                'Desa Lubuk Bandung',
                'Desa Talang Seleman',
                'Desa Tebedak II',
                'Desa Tanjung Lalang',
                'Desa Seri Kembang I',
                'Desa Rengas I',
                'Desa Paya Besar',
                'Desa Rengas II',
                'Desa Seri Kembang II',
                'Desa Seri Kembang III',
                'Kelurahan Payaraman Barat',
                'Kelurahan Payaraman Timur',
            ],
            'Lubuk Keliat' => [
                'Desa Ulak Kembahang',
                'Desa Lubuk Keliat',
                'Desa Embacang',
                'Desa Kasi Raja',
                'Desa Talang Tengah Darat',
                'Desa Betung II',
                'Desa Ketiau',
                'Desa Payalingkung',
                'Desa Betung I',
                'Desa Talang Tengah Laut',
            ],
        ];

        foreach ($data as $namaKecamatan => $daftarDesa) {
            $kecamatan = Kecamatan::firstOrCreate(['nama' => $namaKecamatan]);

            foreach ($daftarDesa as $namaDesa) {
                Desa::firstOrCreate([
                    'kecamatan_id' => $kecamatan->id,
                    'nama' => $namaDesa,
                ]);
            }

            // Hubungkan akun Kecamatan yang udah ada (dari KecamatanSeeder) ke master Kecamatan ini,
            // dicocokkan lewat username 'kecamatan.<slug-nama>' yang formatnya konsisten.
            $slug = Str::slug($namaKecamatan);
            User::where('username', "kecamatan.{$slug}")->update(['kecamatan_id' => $kecamatan->id]);
        }
    }
}